# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Sam's Data Stories
# Description of the Site
description: Data Science Portfolio Site for Samuel T. Shanks, PhD
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: /assets/images/Mad_Sam_disc.jpg

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/portofino.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: sshanks@fastmail.fm 
facebook_username: /
twitter_username: profshanks
instagram_username: /
linkedin_username: profshanks
github_username:  profshanks
youtube_channel_id: /
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: profshanks

# Name of the Author
author-name: profshanks
# URL for the Image of the Author
author-image: /assets/images/Mad_Sam_disc.jpg
# 60 Words About the Author
author-about: In an ideal world, I would analyze data for NASA in the morning, design AI to guide robots in the afternoon, and go watch the sun set from a boat in the evening. I love collaboration; I love solving difficult problems; I am relentlessly curious.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/profshanks

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
